server:
  port: 8000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/user-service/**
          filters:
            - AddRequestHeader=user-request, user-request-value2
            - AddResponseHeader=user-response, user-response-value2
            - CustomFilter
        - id: admin-service
          uri: http://localhost:8082/
          predicates:
            - Path=/admin-service/**
          filters:
            - AddRequestHeader=admin-request, admin-request-value2
            - AddResponseHeader=admin-response, admin-response-value2
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
