INSERT INTO CATALOGS (PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES ('CATALOG-001', 'Berlin', 100, 1500);
INSERT INTO CATALOGS (PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES ('CATALOG-002', 'Seoul', 200, 10000);
INSERT INTO CATALOGS (PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES ('CATALOG-003', 'Busan', 300, 20900);