server:
  port: 8888 # spring-cloud-config default port

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://${user.home}/lozm/git/personal/spring-cloud-playground/config-server/config-repo
          uri: https://github.com/LaOnZenaMoon/spring-cloud-config-server.git
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, busrefresh

logging:
  level:
    root: DEBUG