server:
  port: 8888 # spring-cloud-config default port

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/junlee/lozm/git/personal/spring-cloud-playground/config-server/config-repo
